services:
  cebra-stable:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ryuuua/cebra_nlp:2025.10.24
    container_name: cebra-stable
    profiles: ["stable"]
    ipc: host
    shm_size: "16g"
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
    environment:
      - TZ=Asia/Tokyo
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /workspace/CEBRA_NLP
    volumes:
      - /home/ryua/CEBRA:/workspace:rw
      - /data/cebra/data:/workspace/CEBRA_NLP/data
      - /data/cebra/embedding_cache:/workspace/CEBRA_NLP/embedding_cache
      - /data/cebra/results:/workspace/CEBRA_NLP/results
      - /data/cebra/results_manual:/workspace/CEBRA_NLP/results_manual
      - /data/cebra/wandb:/workspace/CEBRA_NLP/wandb
      - /data/cebra/export:/workspace/CEBRA_NLP/export
      - /data/cebra/logs_manual:/workspace/CEBRA_NLP/logs_manual
      - /data/cebra/hf-cache:/root/.cache/huggingface
    command: sleep infinity
    restart: "no"

  cebra-edge:
    image: nvcr.io/nvidia/pytorch:24.10-py3
    container_name: cebra-edge
    profiles: ["edge"]
    ipc: host
    shm_size: "16g"
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
    environment:
      - TZ=Asia/Tokyo
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /workspace/CEBRA_NLP
    volumes:
      - /home/ryua/CEBRA:/workspace:rw
      - /data/cebra/data:/workspace/CEBRA_NLP/data
      - /data/cebra/embedding_cache:/workspace/CEBRA_NLP/embedding_cache
      - /data/cebra/results:/workspace/CEBRA_NLP/results
      - /data/cebra/results_manual:/workspace/CEBRA_NLP/results_manual
      - /data/cebra/wandb:/workspace/CEBRA_NLP/wandb
      - /data/cebra/export:/workspace/CEBRA_NLP/export
      - /data/cebra/logs_manual:/workspace/CEBRA_NLP/logs_manual
      - /data/cebra/hf-cache:/root/.cache/huggingface
    command: sleep infinity
    restart: "no"
